# Generated by Django 2.2.1 on 2019-05-19 19:05

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(first_name="User 001", last_name="User 001", email="user001@email.com", phone="00000000", address="User 000 Address", description= "User 001 description").save()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_data),
    ]     